# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-25 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='areaa',
            new_name='area',
        ),
    ]
