# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-25 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0002_auto_20170925_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tel',
            field=models.IntegerField(null=True),
        ),
    ]
