# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-25 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0003_auto_20170925_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tel',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
