# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-25 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0005_auto_20170925_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.IntegerField(default=5),
        ),
    ]
